# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.2.dev17+g2c9fa8e.d20221223'
__version_tuple__ = version_tuple = (0, 0, 2, 'dev17', 'g2c9fa8e.d20221223')
