# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev3+ga1937fa.d20221210'
__version_tuple__ = version_tuple = (0, 1, 'dev3', 'ga1937fa.d20221210')
