# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.2.dev1+g1dc9005.d20221211'
__version_tuple__ = version_tuple = (0, 0, 2, 'dev1', 'g1dc9005.d20221211')
